#!/bin/sh

BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`

echo $1

if [ ! -z "$BRANCH_NAME" ] && [ "$BRANCH_NAME" != "HEAD" ] && [ "$SKIP_PREPARE_COMMIT_MSG" != 1 ]; then

    BRANCH_DESC=`echo ${BRANCH_NAME} | cut -d '/' -f2`
    PREFIX=`echo ${BRANCH_DESC} | cut -d '_' -f1`
    PREFIX_IN_COMMIT=$(grep -c "\[#$PREFIX\]" $1)

    if [[ -n "$PREFIX" ]] && ! [[ $PREFIX_IN_COMMIT -ge 1 ]]; then
        sed -i.bak -e "1s~^~[#$PREFIX] ~" $1
    fi

fi
