name: Server CI

on:
    pull_request:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x

            - name: Cache node modules
              id: node-cache
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: npm-

            - name: Install dependencies
              if: steps.node-cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: create env file
              shell: bash
              run: |
                  touch .env
                  echo PASSWORD = ${{ secrets.PASSWORD }} >> .env
                  echo RAW_PASSWORD = ${{ secrets.RAW_PASSWORD }} >> .env
                  echo JWT_SECRET = ${{ secrets.JWT_SECRET }} >> .env
                  cat .env

            - name: Lint & Prettier
              run: npm run style

            - name: Build
              run: npm run build

            - name: Test
              run: npm run test

concurrency:
    group: ${{ github.head_ref }}
    cancel-in-progress: true
